### PR TITLE
Include Printf Test Script

### PR DESCRIPTION
**Pull request by MoonTheRipper**
# this is  a printf project testing script
- the purpose of this is to make sure our functions work well
before we add them to the project Structure.
- inside includes all the formating functions and main function for testing.
-  compile thye script using ```gcc -Wall -Werror -Wextra -pedantic -Wno-format -std=gnu89 _printf.c -o print```

### CODE REVIEW

**Comment by MoonTheRipper** [comment]
- Remember to git pull after a pull request is made.
- Also, after review, if everything is okay, please merge with main and delete the branch

**Comment by MoonTheRipper** [comment]
- Please Try and work out the bug in the formatting functions for:

- %d
- %i
- %x
- %X

**Comment by MoonTheRipper** [comment]
- Also Remember to include the function prototypes to the main Header file in the project structure
This is for the sake of our commit levels.
- copy the  ```_putstr``` and ```_putchar``` function to a file name ```formats.c```
- The ```_printf``` and ```printer``` function in another file  ```printf.c``` that is already present.
- The remaining ```_putint``` and ```_putstr``` can be added later after we figure out the bug
- Remember to incluede the header in each file you create

# Happy Coding C is Fun!

**Review by larinegit — COMMENTED** [review]
already reviewed

**Review by larinegit — APPROVED** [review]

**Comment by MoonTheRipper** [comment]
Thanks for the merge

**Pull request merged**
